### ISSUE TITLE
Docker container healthcheck for CNCLI usage

### ISSUE THREAD

**Issue by adamsthws** [cardano-community/guild-operators#1841]
Hello,

I wonder if it makes sense to request an improvement to the builtin healthcheck of the Docker container? ... 
When enabling CNCLI services by configuring it to run as a docker sidecar container, the sidecar container's built-in healthcheck fails.

Would it be possible to update healthcheck.sh to detect when the container has been started with 'ENTRYPOINT_PROCESS: cncli.sh', and 'command: sync, validate, etc...' and adjust the heathcheck that is performed?

Below is an example docker compose file to illustrate a sidecar config... 
(The CNCLI sidecar container's entrypoint is overridden by setting env variable: ```ENTRYPOINT_PROCESS: cncli.sh```  and ```command: sync```)

```
services:

#  built-in healthcheck works:
  cardano-node:
    image: cardanocommunity/cardano-node:latest
    volumes:
      - cn-sockets:/opt/cardano/cnode/sockets
      - cn-logs:/opt/cardano/cnode/logs
      - cn-guild-db:/opt/cardano/cnode/guild-db

#  built-in healthcheck fails:
  cardano-cncli-sync:
    image: cardanocommunity/cardano-node:latest
    network_mode: service:cardano-node
    volumes:
      - cn-sockets:/opt/cardano/cnode/sockets
      - cn-logs:/opt/cardano/cnode/logs
      - cn-guild-db:/opt/cardano/cnode/guild-db
    environment:
      ENTRYPOINT_PROCESS: cncli.sh                            # Override entrypoint
    command: sync                                             # Entrypoint command
```

Thankyou!
-Adam

**Comment by rdlrt** [comment]
I think the health check in place currently is for the image `cardano-node` while the other scripts will have their own (the current script isnt meant to be used as health check reference point for others). Understandably the sample we have isnt a docker-compose file, what I believe is being requested then is to have a standard fully component-mapped docker-compose presenting health checks for every component (eg: dbsync, ogmios, cncli, etc) and then users can enable/disable individual components from there to their liking.

CC: @TrevorBenson

**Comment by adamsthws** [comment]
Sounds ideal. Would something like this make sense? ...

A component-mapped docker image, allowing users to enable/disable individual components on a per container basis (eg: dbsync, ogmios, cncli, etc), each with a working healthcheck. This allows for modular containers that follow the single responsibility principle, running one process per container.

Perhaps the container's service could be chosen by simply setting an env variable like so ...

Run the container as the default service - Leave commented (or omit from compose file) for default:
#SERVICE="cnode.sh"

Choose to override, eg. using cncli sync instead:
SERVICE="cncli.sh sync"

[[ -z ${SERVICE} ]] && SERVICE="cnode.sh"

An example docker compose:

```
services:

  cardano-node:
    image: cardanocommunity/cardano-node:latest
    volumes:
      - cn-sockets:/opt/cardano/cnode/sockets
      - cn-logs:/opt/cardano/cnode/logs
      - cn-guild-db:/opt/cardano/cnode/guild-db

  cncli-sync:
    image: cardanocommunity/cardano-node:latest
    network_mode: service:cardano-node
    volumes:
      - cn-sockets:/opt/cardano/cnode/sockets
      - cn-logs:/opt/cardano/cnode/logs
      - cn-guild-db:/opt/cardano/cnode/guild-db
    environment:
      SERVICE: "cncli.sh sync"
 ```
